parsers: # array
  - reg: ^.*$
    # 格式化配置文件
    code: |
      module.exports.parse = (raw, { yaml }) => {
        const rawObj = yaml.parse(raw);
        delete rawObj['port']
        delete rawObj['socks-port']
        delete rawObj['allow-lan']
        delete rawObj['mode']
        delete rawObj['log-level']
        delete rawObj['external-controller']
        const updatedObj = { ...rawObj, 'proxy-groups': [], rules: [] };
        return yaml.stringify(updatedObj);
      }
    # 建立自己的配置
    yaml:
      prepend-proxies:
        - name: mDavid_CN
          type: vmess
          server: your_ip
          port: 10086
          uuid: abc
          alterId: 0
          cipher: none
          udp: true

      prepend-proxy-groups: # 策略组
        - name: PROXY
          type: select
          url: http://www.gstatic.com/generate_204
          interval: 300
          proxies:
            - GOOD
            - SUB

        - name: MEDIA
          type: select
          url: http://www.gstatic.com/generate_204
          interval: 300
          proxies:
            - GOOD
            - SUB

        - name: GOOD # 自建的
          type: select
          url: http://www.gstatic.com/generate_204
          interval: 300
          proxies:
            - mDavid_CN

        - name: SUB # 订阅的
          type: url-test
          url: http://www.gstatic.com/generate_204
          interval: 300
          tolerance: 50

        - name: FINAL
          type: select
          proxies:
            - GOOD
            - SUB
            - DIRECT
          ssid-policy:
            default: GOOD


      commands:
        - proxy-groups.SUB.proxies=[]proxyNames|^(?!.*mDavid_CN).*$  # 向指定策略组(SUB)添加订阅中的节点名，可使用正则过滤
        # - proxy-groups.PROXY.proxies.0+DIRECT # 向指定分组(PROXY)第一个位置添加一个 DIRECT 节点名

        # 一些可能用到的正则过滤节点示例，使分组更细致
        # []proxyNames|a                         # 包含a
        # []proxyNames|^(.*)(a|b)+(.*)$          # 包含a或b
        # []proxyNames|^(?=.*a)(?=.*b).*$        # 包含a和b
        # []proxyNames|^((?!b).)*a((?!b).)*$     # 包含a且不包含b
        # []proxyNames|^((?!b|c).)*a((?!b|c).)*$ # 包含a且不包含b或c

      # 添加规则
      prepend-rules: # 规则由上往下遍历，如上面规则已经命中，则不再往下处理
        - RULE-SET,mdavid_direct,DIRECT
        - RULE-SET,douyin,DIRECT
        - RULE-SET,applications,DIRECT
        - RULE-SET,mdavid_proxy,PROXY
        - RULE-SET,globalmedia,MEDIA
        - RULE-SET,icloud,PROXY
        - RULE-SET,apple,PROXY
        - RULE-SET,google,PROXY
        - RULE-SET,tld-not-cn,PROXY
        - RULE-SET,gfw,PROXY
        - RULE-SET,proxy,PROXY
        - RULE-SET,private,DIRECT
        - RULE-SET,lancidr,DIRECT,no-resolve
        - RULE-SET,cncidr,DIRECT,no-resolve
        - GEOIP,LAN,DIRECT,no-resolve
        - GEOIP,CN,DIRECT,no-resolve
        - MATCH,FINAL

      # 添加规则集
      mix-rule-providers:
        icloud:
          type: http
          format: yaml
          interval: 86400
          behavior: domain
          url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/icloud.txt
          path: ./ruleset/loyalsoldier/icloud.yaml
        apple:
          type: http
          format: yaml
          interval: 86400
          behavior: domain
          url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/apple.txt
          path: ./ruleset/loyalsoldier/apple.yaml
        google:
          type: http
          format: yaml
          interval: 86400
          behavior: domain
          url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/google.txt
          path: ./ruleset/loyalsoldier/google.yaml
        proxy:
          type: http
          format: yaml
          interval: 86400
          behavior: domain
          url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/proxy.txt
          path: ./ruleset/loyalsoldier/proxy.yaml
        private:
          type: http
          format: yaml
          interval: 86400
          behavior: domain
          url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/private.txt
          path: ./ruleset/loyalsoldier/private.yaml
        gfw:
          type: http
          format: yaml
          interval: 86400
          behavior: domain
          url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/gfw.txt
          path: ./ruleset/loyalsoldier/gfw.yaml
        tld-not-cn:
          type: http
          format: yaml
          interval: 86400
          behavior: domain
          url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/tld-not-cn.txt
          path: ./ruleset/loyalsoldier/tld-not-cn.yaml
        cncidr:
          type: http
          format: yaml
          interval: 86400
          behavior: ipcidr
          url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/cncidr.txt
          path: ./ruleset/loyalsoldier/cncidr.yaml
        lancidr:
          type: http
          format: yaml
          interval: 86400
          behavior: ipcidr
          url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/lancidr.txt
          path: ./ruleset/loyalsoldier/lancidr.yaml
        applications:
          type: http
          format: yaml
          interval: 86400
          behavior: classical
          url: https://raw.githubusercontent.com/Loyalsoldier/clash-rules/release/applications.txt
          path: ./ruleset/loyalsoldier/applications.yaml
        globalmedia:
          type: http
          format: yaml
          interval: 86400
          behavior: classical
          url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/GlobalMedia/GlobalMedia_Classical.yaml
          path: ./ruleset/blackmatrix7/globalmedia.yaml
        douyin:
          type: http
          format: yaml
          interval: 86400
          behavior: classical
          url: https://raw.githubusercontent.com/blackmatrix7/ios_rule_script/master/rule/Clash/DouYin/DouYin.yaml
          path: ./ruleset/blackmatrix7/douyin.yaml
        mdavid_proxy:
          type: http
          format: yaml
          interval: 86400
          behavior: classical
          url: https://raw.githubusercontent.com/HEUDavid/svr/main/v2ray/clash/proxy.yaml
          path: ./ruleset/mdavid/proxy.yaml
        mdavid_direct:
          type: http
          format: yaml
          interval: 86400
          behavior: classical
          url: https://raw.githubusercontent.com/HEUDavid/svr/main/v2ray/clash/direct.yaml
          path: ./ruleset/mdavid/direct.yaml
